version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - 'db_data:/var/lib/mysql'
     restart: unless-stopped
     env_file:
       - 'config/envvars'

   kawf:
     depends_on:
       - db
     image: kawf:latest
     ports:
       - "80:80"
     restart: unless-stopped
     env_file:
       - 'config/envvars'

volumes:
    db_data: {}
